import { NodeTypes, EdgeTypes } from 'reactflow';
import {
  StartEvent,
  EndEvent,
  IntermediateThrowEvent,
  IntermediateCatchEvent,
  TimerEvent,
  MessageEvent,
  SignalEvent,
  Task,
  UserTask,
  ServiceTask,
  ScriptTask,
  BusinessRuleTask,
  ManualTask,
  ReceiveTask,
  SendTask,
  ExclusiveGateway,
  ParallelGateway,
  InclusiveGateway,
  EventBasedGateway,
  ComplexGateway,
  DataObject,
  DataStore,
  Pool,
  Lane,
  MessageFlow,
  Association,
} from './BpmnNodes';

// Export static type objects that won't change between renders
export const nodeTypes: NodeTypes = {
  startEvent: StartEvent,
  endEvent: EndEvent,
  intermediateThrowEvent: IntermediateThrowEvent,
  intermediateCatchEvent: IntermediateCatchEvent,
  timerEvent: TimerEvent,
  messageEvent: MessageEvent,
  signalEvent: SignalEvent,
  task: Task,
  userTask: UserTask,
  serviceTask: ServiceTask,
  scriptTask: ScriptTask,
  businessRuleTask: BusinessRuleTask,
  manualTask: ManualTask,
  receiveTask: ReceiveTask,
  sendTask: SendTask,
  exclusiveGateway: ExclusiveGateway,
  parallelGateway: ParallelGateway,
  inclusiveGateway: InclusiveGateway,
  eventBasedGateway: EventBasedGateway,
  complexGateway: ComplexGateway,
  dataObject: DataObject,
  dataStore: DataStore,
  pool: Pool,
  lane: Lane,
} as const;

export const edgeTypes: EdgeTypes = {
  messageFlow: MessageFlow,
  association: Association,
} as const;
